### ISSUE TITLE
DB Seeds for front-end

### ISSUE THREAD

**Issue by luzlab** [machinabio/limbforge-service#11]
What information is needed to seed the front-end rails app?

@kaitlynhova Can you just copy/paste a JSON that I can send you from the backend to start a new limbforge rails app?

**Comment by kaitlynhova** [comment]
Whiteboarding times:
![unnamed](https://cloud.githubusercontent.com/assets/5474124/26707311/d5e4eac8-46f8-11e7-995f-a455339136b0.jpg)

1. RESPONSE: DATA URI
2. RESPONSE: ZIP FILE DOWNLOAD
3. RESPONSE: 
```
{"transradial": true, etc }
```
*true/false = if we have a component for that amputation level or not

4. RESPONSE:
```
[
    {
            slug: 'xrp-arm'
            name: 'XRP arm',
            icon:  'https://www.AWSurlhere',
            creator: 'Limbforge',
            component_type: 'passive',
            weight: '250-350g',
            description: 'The XRP Arm is a lightweight, highly cosmetic passive device with several terminal device options. uses:  passive cosmetic, social functions',
            uses: 'social occasions, supporting objects',
            print_time: '14-20hrs'
    }
]
```
5. RESPONSE

```
[
    {
       name: 'C2',
       step: 0.5,
       upper_range: 28,
       measurement_unit: "cm",
       lower_range: 20,
       default: 25,
       instructions: 'instructions go here'
    }
]
```

6. RESPONSE

```
[
    {
       slug: 'terminal-device-name'
       name: 'terminal device name',
    }
]
```

**Comment by luzlab** [comment]
Perfect! Let's make 6 issues - one for each endpoint.

**Comment by luzlab** [comment]
I think we're good. All of the other issues have been created (and are nearly done).
